squazic_highline_guide_homepage:
    pattern:  /
    defaults: { _controller: SquazicHighlineGuideBundle:Default:index }

squazic_highline_guide_data:
    pattern:  /data
    defaults: { _controller: SquazicHighlineGuideBundle:Default:data }

SquazicHighlineGuideBundle_artwork:
    resource: "@SquazicHighlineGuideBundle/Resources/config/routing/artwork.yml"
    prefix:   /admin/artwork

SquazicHighlineGuideBundle_artist:
    resource: "@SquazicHighlineGuideBundle/Resources/config/routing/artist.yml"
    prefix:   /admin/artist

security_login:
    pattern:  /login
    defaults: { _controller: SquazicHighlineGuideBundle:Default:login }

security_check:
    pattern:  /admin/login_check

security_logout:
    pattern:  /admin/logout
